### ISSUE TITLE
E10 when using custom checkstyle.xml

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-checkstyle#19]
# Bug

## Actual Behavior
User is experiencing an E10 error when trying to analyze this repo: https://github.com/dropwizard/dropwizard

- Code Climate Support has tested against "beta" and stable channels. (both errored)
- Support has also increased the max memory threshold to 3.73 gigs (still errored)

- customer's repo has a different checkstyle.xml (compared to [the one](https://docs.codeclimate.com/docs/checkstyle#section-configure-the-engine) the engine is shipped with)
- replacing customer's checkstyle.xml with [CC's](https://docs.codeclimate.com/docs/checkstyle#section-configure-the-engine) allows the build to complete.

----

BTW: analysis does work with the CLI, but I think it might be related to CLI silently failing?

----

## Expected Behavior
- completed analysis
- error indicating what might be wrong

## Relevant links
- customer's repo: https://github.com/dropwizard/dropwizard

**Comment by arteam** [comment]
Hi! I am the reporter of the issue, happy to help with debugging. 

I tried to check different configurations in our `.codeclimate.yml` file, but without success. If add the checkstyle plugin to our Maven build, it seems to be working fine and picking up the config. At least I see some violations in the console.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-checkstyle-plugin</artifactId>
    <version>2.17</version>
    <configuration>
        <configLocation>checkstyle.xml</configLocation>
        <encoding>UTF-8</encoding>
        <consoleOutput>true</consoleOutput>
        <failOnViolation>false</failOnViolation>
    </configuration>
</plugin>
```

From the user's perspective it would be nice to see an error log from the engine in the web interface instead of a generic error.

**Comment by arteam** [comment]
Without the Maven plugin and a downloaded checkstyle jar file, analysys seems to be working too: 
```shell
java -jar checkstyle-8.2-all.jar -c checkstyle.xml $(find -name *.java | grep -v "dropwizard-archetypes" | paste -sd " ")
```

**Comment by filipesperandio** [comment]
@arteam @efueger Checkstyle has a tricky way to handle the output of some violations, so it is indeed not helpful.

What is happening here is that the default `Severity` for `UnnecessaryParentheses` is defined as `ERROR` and `checkstyle` itself abort the execution on those. To overcome this behavior we change the default `Severity` of all violations to be `WARNING` within the builtin `checkstyle.xml` the engine provides, that can be done in the custom file as well and might solve this problem:
```xml
...
<module name="Checker">
    <property name="severity" value="warning"/>
    ...
```
I will make sure that we add this to our documentation as well.

**Comment by arteam** [comment]
Thanks, it worked! 

https://github.com/dropwizard/dropwizard/commit/d3a7b57dfd13d7bfa976c751c6483b75c38eee64
https://codeclimate.com/github/dropwizard/dropwizard/builds/15
