### ISSUE TITLE
Upgrade Checkstyle to latest version 8.32

### ISSUE THREAD

**Issue by maxim-zaman-heb** [codeclimate/codeclimate-checkstyle#27]
Current Codeclimate Checkstyle version 8.30 is incompatible with one of Google Code Style rules (NoWhitespaceBeforeCheck):
https://github.com/checkstyle/checkstyle/issues/8124

When running Checkstyle with Google Style rules, we get error:
`com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Token "LABELED_STAT" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.NoWhitespaceBeforeCheck`

Token "LABELED_STAT" was added to acceptable tokens list in Checkstyle release 8.32

**Comment by mr-smithers-excellent** [comment]
Experiencing the same issue here. Works fine when running locally with Checkstyle version `8.32`, but errors when running against CodeClimate's Checstyle on `8.30`. 

Looks like a relatively simple change to [CHECKSTYLE_VERSION](https://github.com/codeclimate/codeclimate-checkstyle/blob/master/CHECKSTYLE_VERSION)

**Comment by efueger** [comment]
Hi @maxim-zaman-heb and @mr-smithers-excellent -

- Can you try pushing a new commit?

We've [updated](https://github.com/codeclimate/codeclimate-checkstyle/commit/eb0136a4a72f26fda7a5e773744cade59312e0d5) to 8.32!

Let me know how it goes,
Emily, Code Climate Support

**Comment by maxim-zaman-heb** [comment]
Hey! Could you push up a new docker version to https://hub.docker.com/r/codeclimate/codeclimate/tags ?

Thanks!

**Comment by mr-smithers-excellent** [comment]
@efueger - we're back in business! Thanks for your help on this.

**Comment by maxim-zaman-heb** [comment]
Thanks y'all!
